language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
script:
  - python manage.py syncdb --noinput
  - python manage.py collectstatic --noinput
  - python manage.py test accounts music noms servers tournaments dashboard chat admin gallery benchmark
